@startchen

entity Player {
  id
  fullName
  email
  phone
}

entity Admin {
  id
}

entity AdminRole {
  id
  role
}

entity Mission {
  id
  name
  description
}

entity Event {
  id
  name
}

entity PlayerOrganization {
  id
  name
}

entity Submission {
  type
  data
}

entity PointTransaction {
  type
  data
}

entity Badge {
  id
  type
}

entity Reward {
  id
  type
}

entity RewardRedemption {
  id
}

relationship wins {
}

relationship has_a {
}

relationship has_b {
}

relationship generates_a {
}

relationship generates_b {
}

relationship submits {
}

relationship completes {
}

relationship participates_in {
}

relationship belongs_to {
}

relationship can_redeem {
}

relationship manages {
}

relationship creates {
}

relationship reviews {
}

Player -N- completes
completes -M- Mission

Player -N- participates_in
participates_in -M- Event

Player -N- belongs_to
belongs_to -M- PlayerOrganization

Player -N- wins
wins -M- Badge

Player -1- submits
submits -N- Submission

Player -1- has_a
has_a -N- PointTransaction

Submission -1- generates_a
generates_a -1- PointTransaction

Mission -1- has_b
has_b -N- Submission

Event -1- generates_b
generates_b -N- PointTransaction

@endchen

// Additional Tables - Participation