@startchen

entity profiles {
  full_name
  email
  phone
  organization_name
  userRole
}

entity user_roles {
  role
}

relationship assigned_to {
}

profiles -1- assigned_to
assigned_to -1- user_roles

@endchen